title: Haozhe An
logo: ./IMG_2712.JPG
tagline: I don't like haze, as the anagram of my name suggests, "Ah, noHaze!"
description: > # your text below (remove <br> elements if you don't need line breaks)

  Email: haozhe@umd.edu
  <br>
  <br>
  <a href="https://www.linkedin.com/in/haozhe-an/">View My LinkedIn Profile</a> 
  <br>
  <br>
  <a href="https://scholar.google.com/citations?user=ZBVLUFYAAAAJ&hl=en">View My Google Scholar Profile</a> 
google_analytics: UA-147271754-1
theme: jekyll-theme-minimal
